-- CreateTable
CREATE TABLE "MENSAJE" (
    "id" SERIAL NOT NULL,
    "proyecto_id" INTEGER NOT NULL,
    "proyecto_docente_id" INTEGER NOT NULL,
    "contenido" TEXT NOT NULL,
    "creado_en" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "MENSAJE_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "MENSAJE" ADD CONSTRAINT "MENSAJE_proyecto_id_fkey" FOREIGN KEY ("proyecto_id") REFERENCES "PROYECTO_CLASE_ESPEJO"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MENSAJE" ADD CONSTRAINT "MENSAJE_proyecto_docente_id_fkey" FOREIGN KEY ("proyecto_docente_id") REFERENCES "PROYECTO_DOCENTE"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
