-- AlterTable
ALTER TABLE "USUARIO" ADD COLUMN "tipo_documento" TEXT NOT NULL DEFAULT 'DNI';

-- AlterTable
ALTER TABLE "INSTITUCION" ADD COLUMN "codigo_pais" TEXT NOT NULL DEFAULT '';
ALTER TABLE "INSTITUCION" ADD COLUMN "estado" TEXT NOT NULL DEFAULT '';
ALTER TABLE "INSTITUCION" ADD COLUMN "ciudad" TEXT NOT NULL DEFAULT '';
ALTER TABLE "INSTITUCION" ADD COLUMN "telefono" TEXT NOT NULL DEFAULT '';
