-- AlterTable
ALTER TABLE "SOLICITUD_CLASE_ESPEJO" ADD COLUMN     "asignacion_destino_id" INTEGER;

-- AddForeignKey
ALTER TABLE "SOLICITUD_CLASE_ESPEJO" ADD CONSTRAINT "SOLICITUD_CLASE_ESPEJO_asignacion_destino_id_fkey" FOREIGN KEY ("asignacion_destino_id") REFERENCES "ASIGNACION_DOCENTE"("id") ON DELETE SET NULL ON UPDATE CASCADE;
