-- CreateTable
CREATE TABLE "INSTITUCION" (
    "id" SERIAL NOT NULL,
    "nombre" TEXT NOT NULL,
    "pais" TEXT NOT NULL,
    "correo_institucional" TEXT NOT NULL,
    "activa" BOOLEAN NOT NULL,

    CONSTRAINT "INSTITUCION_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "USUARIO" (
    "id" SERIAL NOT NULL,
    "nombres" TEXT NOT NULL,
    "apellidos" TEXT NOT NULL,
    "correo" TEXT NOT NULL,
    "password_hash" TEXT NOT NULL,
    "activo" BOOLEAN NOT NULL,

    CONSTRAINT "USUARIO_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "AGENTE_INTERNACIONALIZACION" (
    "id" SERIAL NOT NULL,
    "usuario_id" INTEGER NOT NULL,
    "institucion_id" INTEGER NOT NULL,
    "cargo" TEXT NOT NULL,

    CONSTRAINT "AGENTE_INTERNACIONALIZACION_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "DOCENTE" (
    "id" SERIAL NOT NULL,
    "usuario_id" INTEGER NOT NULL,
    "grado_academico" TEXT NOT NULL,
    "especialidad" TEXT NOT NULL,

    CONSTRAINT "DOCENTE_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "DOCENTE_INSTITUCION" (
    "id" SERIAL NOT NULL,
    "docente_id" INTEGER NOT NULL,
    "institucion_id" INTEGER NOT NULL,
    "numero_empleado" TEXT NOT NULL,
    "activo" BOOLEAN NOT NULL,

    CONSTRAINT "DOCENTE_INSTITUCION_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "MATERIA" (
    "id" SERIAL NOT NULL,
    "institucion_id" INTEGER NOT NULL,
    "clave" TEXT NOT NULL,
    "nombre" TEXT NOT NULL,
    "programa_educativo" TEXT NOT NULL,
    "descripcion" TEXT NOT NULL,
    "activa" BOOLEAN NOT NULL,

    CONSTRAINT "MATERIA_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ASIGNACION_DOCENTE" (
    "id" SERIAL NOT NULL,
    "docente_institucion_id" INTEGER NOT NULL,
    "materia_id" INTEGER NOT NULL,
    "periodo_escolar" TEXT NOT NULL,

    CONSTRAINT "ASIGNACION_DOCENTE_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SOLICITUD_CLASE_ESPEJO" (
    "id" SERIAL NOT NULL,
    "asignacion_origen_id" INTEGER NOT NULL,
    "institucion_destino_id" INTEGER NOT NULL,
    "materia_destino_id" INTEGER,
    "titulo" TEXT NOT NULL,
    "objetivo" TEXT NOT NULL,
    "fecha_propuesta" DATE NOT NULL,
    "estado" TEXT NOT NULL,
    "creada_en" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "SOLICITUD_CLASE_ESPEJO_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "REVISION_SOLICITUD" (
    "id" SERIAL NOT NULL,
    "solicitud_id" INTEGER NOT NULL,
    "agente_id" INTEGER NOT NULL,
    "etapa" TEXT NOT NULL,
    "decision" TEXT NOT NULL,
    "comentario" TEXT NOT NULL,
    "revisada_en" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "REVISION_SOLICITUD_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PROYECTO_CLASE_ESPEJO" (
    "id" SERIAL NOT NULL,
    "solicitud_id" INTEGER NOT NULL,
    "estado" TEXT NOT NULL,
    "fecha_inicio" DATE NOT NULL,
    "fecha_fin" DATE NOT NULL,
    "plataforma" TEXT NOT NULL,

    CONSTRAINT "PROYECTO_CLASE_ESPEJO_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PROYECTO_DOCENTE" (
    "id" SERIAL NOT NULL,
    "proyecto_id" INTEGER NOT NULL,
    "asignacion_docente_id" INTEGER NOT NULL,
    "rol" TEXT NOT NULL,

    CONSTRAINT "PROYECTO_DOCENTE_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PLANIFICACION_CONJUNTA" (
    "id" SERIAL NOT NULL,
    "proyecto_id" INTEGER NOT NULL,
    "objetivos_acordados" TEXT NOT NULL,
    "temas_acordados" TEXT NOT NULL,
    "metodologia" TEXT NOT NULL,
    "plataforma" TEXT NOT NULL,
    "estado" TEXT NOT NULL,
    "creada_en" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PLANIFICACION_CONJUNTA_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PARTICIPACION_PLANIFICACION" (
    "id" SERIAL NOT NULL,
    "planificacion_id" INTEGER NOT NULL,
    "proyecto_docente_id" INTEGER NOT NULL,
    "estatus_confirmacion" TEXT NOT NULL,
    "confirmada_en" TIMESTAMP(3),

    CONSTRAINT "PARTICIPACION_PLANIFICACION_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "REPORTE_PLANIFICACION" (
    "id" SERIAL NOT NULL,
    "planificacion_id" INTEGER NOT NULL,
    "acuerdos" TEXT NOT NULL,
    "calendario" TEXT NOT NULL,
    "actividades_acordadas" TEXT NOT NULL,
    "generado_en" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "REPORTE_PLANIFICACION_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SESION" (
    "id" SERIAL NOT NULL,
    "proyecto_id" INTEGER NOT NULL,
    "titulo" TEXT NOT NULL,
    "fecha_hora" TIMESTAMP(3) NOT NULL,
    "enlace_virtual" TEXT NOT NULL,
    "estado" TEXT NOT NULL,

    CONSTRAINT "SESION_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ACTIVIDAD" (
    "id" SERIAL NOT NULL,
    "proyecto_id" INTEGER NOT NULL,
    "titulo" TEXT NOT NULL,
    "instrucciones" TEXT NOT NULL,
    "fecha_limite" DATE NOT NULL,

    CONSTRAINT "ACTIVIDAD_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "REPORTE_CLASE_CONJUNTA" (
    "id" SERIAL NOT NULL,
    "sesion_id" INTEGER NOT NULL,
    "desarrollo_clase" TEXT NOT NULL,
    "total_asistentes" INTEGER NOT NULL,
    "incidencias" TEXT NOT NULL,
    "acuerdos_siguiente_sesion" TEXT NOT NULL,
    "estado" TEXT NOT NULL,
    "creado_en" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "REPORTE_CLASE_CONJUNTA_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PARTICIPACION_REPORTE" (
    "id" SERIAL NOT NULL,
    "reporte_clase_id" INTEGER NOT NULL,
    "proyecto_docente_id" INTEGER NOT NULL,
    "observaciones" TEXT NOT NULL,
    "confirmado_en" TIMESTAMP(3),

    CONSTRAINT "PARTICIPACION_REPORTE_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "EVIDENCIA" (
    "id" SERIAL NOT NULL,
    "proyecto_id" INTEGER NOT NULL,
    "sesion_id" INTEGER,
    "tipo" TEXT NOT NULL,
    "archivo_url" TEXT NOT NULL,
    "registrada_en" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "EVIDENCIA_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "EVALUACION" (
    "id" SERIAL NOT NULL,
    "proyecto_id" INTEGER NOT NULL,
    "instrumento" TEXT NOT NULL,
    "resultado" TEXT NOT NULL,
    "observaciones" TEXT NOT NULL,

    CONSTRAINT "EVALUACION_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "AGENTE_INTERNACIONALIZACION_usuario_id_key" ON "AGENTE_INTERNACIONALIZACION"("usuario_id");

-- CreateIndex
CREATE UNIQUE INDEX "DOCENTE_usuario_id_key" ON "DOCENTE"("usuario_id");

-- CreateIndex
CREATE UNIQUE INDEX "PROYECTO_CLASE_ESPEJO_solicitud_id_key" ON "PROYECTO_CLASE_ESPEJO"("solicitud_id");

-- CreateIndex
CREATE UNIQUE INDEX "PLANIFICACION_CONJUNTA_proyecto_id_key" ON "PLANIFICACION_CONJUNTA"("proyecto_id");

-- CreateIndex
CREATE UNIQUE INDEX "REPORTE_CLASE_CONJUNTA_sesion_id_key" ON "REPORTE_CLASE_CONJUNTA"("sesion_id");

-- AddForeignKey
ALTER TABLE "AGENTE_INTERNACIONALIZACION" ADD CONSTRAINT "AGENTE_INTERNACIONALIZACION_usuario_id_fkey" FOREIGN KEY ("usuario_id") REFERENCES "USUARIO"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AGENTE_INTERNACIONALIZACION" ADD CONSTRAINT "AGENTE_INTERNACIONALIZACION_institucion_id_fkey" FOREIGN KEY ("institucion_id") REFERENCES "INSTITUCION"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DOCENTE" ADD CONSTRAINT "DOCENTE_usuario_id_fkey" FOREIGN KEY ("usuario_id") REFERENCES "USUARIO"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DOCENTE_INSTITUCION" ADD CONSTRAINT "DOCENTE_INSTITUCION_docente_id_fkey" FOREIGN KEY ("docente_id") REFERENCES "DOCENTE"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DOCENTE_INSTITUCION" ADD CONSTRAINT "DOCENTE_INSTITUCION_institucion_id_fkey" FOREIGN KEY ("institucion_id") REFERENCES "INSTITUCION"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MATERIA" ADD CONSTRAINT "MATERIA_institucion_id_fkey" FOREIGN KEY ("institucion_id") REFERENCES "INSTITUCION"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ASIGNACION_DOCENTE" ADD CONSTRAINT "ASIGNACION_DOCENTE_docente_institucion_id_fkey" FOREIGN KEY ("docente_institucion_id") REFERENCES "DOCENTE_INSTITUCION"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ASIGNACION_DOCENTE" ADD CONSTRAINT "ASIGNACION_DOCENTE_materia_id_fkey" FOREIGN KEY ("materia_id") REFERENCES "MATERIA"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SOLICITUD_CLASE_ESPEJO" ADD CONSTRAINT "SOLICITUD_CLASE_ESPEJO_asignacion_origen_id_fkey" FOREIGN KEY ("asignacion_origen_id") REFERENCES "ASIGNACION_DOCENTE"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SOLICITUD_CLASE_ESPEJO" ADD CONSTRAINT "SOLICITUD_CLASE_ESPEJO_institucion_destino_id_fkey" FOREIGN KEY ("institucion_destino_id") REFERENCES "INSTITUCION"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SOLICITUD_CLASE_ESPEJO" ADD CONSTRAINT "SOLICITUD_CLASE_ESPEJO_materia_destino_id_fkey" FOREIGN KEY ("materia_destino_id") REFERENCES "MATERIA"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "REVISION_SOLICITUD" ADD CONSTRAINT "REVISION_SOLICITUD_solicitud_id_fkey" FOREIGN KEY ("solicitud_id") REFERENCES "SOLICITUD_CLASE_ESPEJO"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "REVISION_SOLICITUD" ADD CONSTRAINT "REVISION_SOLICITUD_agente_id_fkey" FOREIGN KEY ("agente_id") REFERENCES "AGENTE_INTERNACIONALIZACION"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PROYECTO_CLASE_ESPEJO" ADD CONSTRAINT "PROYECTO_CLASE_ESPEJO_solicitud_id_fkey" FOREIGN KEY ("solicitud_id") REFERENCES "SOLICITUD_CLASE_ESPEJO"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PROYECTO_DOCENTE" ADD CONSTRAINT "PROYECTO_DOCENTE_proyecto_id_fkey" FOREIGN KEY ("proyecto_id") REFERENCES "PROYECTO_CLASE_ESPEJO"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PROYECTO_DOCENTE" ADD CONSTRAINT "PROYECTO_DOCENTE_asignacion_docente_id_fkey" FOREIGN KEY ("asignacion_docente_id") REFERENCES "ASIGNACION_DOCENTE"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PLANIFICACION_CONJUNTA" ADD CONSTRAINT "PLANIFICACION_CONJUNTA_proyecto_id_fkey" FOREIGN KEY ("proyecto_id") REFERENCES "PROYECTO_CLASE_ESPEJO"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PARTICIPACION_PLANIFICACION" ADD CONSTRAINT "PARTICIPACION_PLANIFICACION_planificacion_id_fkey" FOREIGN KEY ("planificacion_id") REFERENCES "PLANIFICACION_CONJUNTA"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PARTICIPACION_PLANIFICACION" ADD CONSTRAINT "PARTICIPACION_PLANIFICACION_proyecto_docente_id_fkey" FOREIGN KEY ("proyecto_docente_id") REFERENCES "PROYECTO_DOCENTE"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "REPORTE_PLANIFICACION" ADD CONSTRAINT "REPORTE_PLANIFICACION_planificacion_id_fkey" FOREIGN KEY ("planificacion_id") REFERENCES "PLANIFICACION_CONJUNTA"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SESION" ADD CONSTRAINT "SESION_proyecto_id_fkey" FOREIGN KEY ("proyecto_id") REFERENCES "PROYECTO_CLASE_ESPEJO"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ACTIVIDAD" ADD CONSTRAINT "ACTIVIDAD_proyecto_id_fkey" FOREIGN KEY ("proyecto_id") REFERENCES "PROYECTO_CLASE_ESPEJO"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "REPORTE_CLASE_CONJUNTA" ADD CONSTRAINT "REPORTE_CLASE_CONJUNTA_sesion_id_fkey" FOREIGN KEY ("sesion_id") REFERENCES "SESION"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PARTICIPACION_REPORTE" ADD CONSTRAINT "PARTICIPACION_REPORTE_reporte_clase_id_fkey" FOREIGN KEY ("reporte_clase_id") REFERENCES "REPORTE_CLASE_CONJUNTA"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PARTICIPACION_REPORTE" ADD CONSTRAINT "PARTICIPACION_REPORTE_proyecto_docente_id_fkey" FOREIGN KEY ("proyecto_docente_id") REFERENCES "PROYECTO_DOCENTE"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EVIDENCIA" ADD CONSTRAINT "EVIDENCIA_proyecto_id_fkey" FOREIGN KEY ("proyecto_id") REFERENCES "PROYECTO_CLASE_ESPEJO"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EVIDENCIA" ADD CONSTRAINT "EVIDENCIA_sesion_id_fkey" FOREIGN KEY ("sesion_id") REFERENCES "SESION"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EVALUACION" ADD CONSTRAINT "EVALUACION_proyecto_id_fkey" FOREIGN KEY ("proyecto_id") REFERENCES "PROYECTO_CLASE_ESPEJO"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
